name: Secret Demo
on:
  push:
    branches:
      - master
jobs:
  demo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verificar se API_KEY está configurada
        run: |
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY não está configurada!"
            exit 1
          else
            echo "API_KEY configurada com sucesso!"
          fi